package com.thingtrack.konekti.map.mobile.component;

import org.vaadin.henrik.superimmediatetextfield.SuperImmediateTextField;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.Embedded;
import com.vaadin.ui.HorizontalLayout;

@SuppressWarnings("serial")
public class ButtonSearch extends CustomComponent {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private SuperImmediateTextField textSearchButton;
	@AutoGenerated
	private Embedded searchIcon;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	private final static String SEARCH_TEST = "  Buscar Feria ... ";
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ButtonSearch() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		addStyleName("searchbutton");
		
		// TODO add user code here
		searchIcon.setStyleName("icon-search");
		
		textSearchButton.setStyleName("text-search");		
		textSearchButton.setInputPrompt(SEARCH_TEST);
	}

	public SuperImmediateTextField getSearchBox() {
		return textSearchButton;
		
	}
	
	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// searchIcon
		searchIcon = new Embedded();
		searchIcon.setImmediate(false);
		searchIcon.setWidth("40px");
		searchIcon.setHeight("40px");
		searchIcon.setSource(new ThemeResource("linegraphics/search.png"));
		searchIcon.setType(1);
		searchIcon.setMimeType("image/png");
		mainLayout.addComponent(searchIcon);
		mainLayout.setComponentAlignment(searchIcon, new Alignment(33));
		
		// textSearchButton
		textSearchButton = new SuperImmediateTextField();
		textSearchButton.setStyleName("text-search");
		textSearchButton.setImmediate(false);
		textSearchButton.setWidth("100.0%");
		textSearchButton.setHeight("40px");
		mainLayout.addComponent(textSearchButton);
		mainLayout.setExpandRatio(textSearchButton, 1.0f);
		mainLayout.setComponentAlignment(textSearchButton, new Alignment(33));
		
		return mainLayout;
	}

}
